# Path to Database
db_path = ""

# Table Information
table_name = 'pitchfx'
sql_create = ""

columns = ('date',
           'year',
           'month',
           'day',
           'away_team',
           'home_team',
           'inning',
           'half',
           'away_team_runs',
           'home_team_runs',
           'batter',
           'pitcher',
           'stand',
           'p_throws',
           'b',
           's',
           'o',
           'ab_des',
           'event',
           'r1',
           'r2',
           'r3',
           'rbi',
           'r2r3',
           'balls',
           'strikes',
           'pitch_des',
           'id',
           'type',
           'code',
           'tfs',
           'x',
           'y',
           'start_speed',
           'end_speed',
           'sz_top',
           'sz_bot',
           'pfx_x',
           'pfx_z',
           'px',
           'pz',
           'x0',
           'y0',
           'z0',
           'vx0',
           'vy0',
           'vz0',
           'ax',
           'ay',
           'az',
           'break_y',
           'break_angle',
           'break_length',
           'pitch_type',
           'type_confidence',
           'zone',
           'nasty',
           'spin_dir',
           'spin_rate'
           )
